import type { ModernAudit } from './modern-audit';
export const auditRows: { id: number; category: string; name: string; modern: ModernAudit }[] = [
  {
    id: 1,
    category: '章节',
    name: '基础用法',
    modern: {
      status: '已实现',
      note: 'useSchemaForm 返回表单组件与 FormApi，所有示例与业务集成共用这一套配置和实现。',
      source: 'src/libs/form/useSchemaForm.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts; src/labs/form-engine/schema-experiments.ts',
    },
  },
  {
    id: 2,
    category: '章节',
    name: '18 种内置控件',
    modern: {
      status: '已实现',
      note: '内置 antdv-next 控件映射、组件对象及注册别名，支持 AutoComplete/Mentions/按钮等。',
      source: 'src/libs/form/controls.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#registry; schema-experiments.ts',
    },
  },
  {
    id: 3,
    category: '章节',
    name: '查询表单',
    modern: {
      status: '有意差异',
      note: '所有 submit 入口均校验，失败返回 undefined 且不调用业务提交；修正本地 Vben 直接 submit 的无效提交路径。隐藏停规则，查询折叠仍验证。',
      source: 'src/libs/form/core/api.ts',
      evidence:
        'tests/unit/schema-form-api.spec.ts; src/labs/form-engine/schema-experiments.ts#submit',
    },
  },
  {
    id: 4,
    category: '章节',
    name: '表单分组',
    modern: {
      status: '已实现',
      note: 'type:group/children、独立折叠、错误自动展开、title/extra、class、hide/name；隐藏保值停规则。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#group',
    },
  },
  {
    id: 5,
    category: '章节',
    name: '动态数组字段',
    modern: {
      status: '已实现',
      note: '数组增删、min/max/createRow、嵌套行路径和行上下文；与参考一样使用索引 key，未新增移动 API 或稳定行 ID。',
      source: 'src/libs/form/core/runtime.ts; src/libs/form/core/render.ts',
      evidence:
        'tests/unit/schema-form-api.spec.ts; src/labs/form-engine/schema-experiments.ts#array',
    },
  },
  {
    id: 6,
    category: '章节',
    name: '表单值编解码',
    modern: {
      status: '已实现',
      note: 'codec encode/decode、setSubmitValues；提交值和原始值类型独立，解析不改写模型。',
      source: 'src/libs/form/core/api.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts',
    },
  },
  {
    id: 7,
    category: '章节',
    name: '性能基准',
    modern: {
      status: '已测量',
      note: '真实本地 Vben runtime 同配置 100/300 字段对照，以及 Chrome 100 局部重绘检查。runtime 测量不代表整页 DOM 性能。',
      source: 'scripts/form/compare-vben-form-runtime.mjs',
      evidence:
        'docs/spec/vben-form-runtime-comparison.json; src/labs/form-engine/schema-experiments.ts#subscriptions',
    },
  },
  {
    id: 8,
    category: '适配器',
    name: 'setupSchemaForm / globalShareState',
    modern: {
      status: '部分排除',
      note: 'setupSchemaForm 提供单 UI 组件/模型/命名规则注册；多 UI globalShareState 按用户要求排除。',
      source: 'src/libs/form/config.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#registry',
    },
  },
  {
    id: 9,
    category: '适配器',
    name: 'modelPropNameMap / baseModelPropName',
    modern: {
      status: '已实现',
      note: '支持 baseModelPropName、modelPropNameMap 和字段 modelPropName；antd 控件内置模型映射。',
      source: 'src/libs/form/controls.ts; src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#registry',
    },
  },
  {
    id: 10,
    category: '适配器',
    name: '自定义组件 / AutoComplete / Mentions / 按钮等',
    modern: {
      status: '已实现',
      note: '内置 antdv-next 控件映射、组件对象及注册别名，支持 AutoComplete/Mentions/按钮等。',
      source: 'src/libs/form/controls.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#registry; schema-experiments.ts',
    },
  },
  {
    id: 11,
    category: '适配器',
    name: 'changeEventFallback',
    modern: {
      status: '已实现',
      note: 'changeEventFallback 支持仅 change 的控件；相同值不重复写入，保留用户事件回调。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#registry',
    },
  },
  {
    id: 12,
    category: '适配器',
    name: 'emptyStateValue',
    modern: {
      status: '已实现',
      note: 'emptyStateValue 支持全局、公共、字段空值配置，模型 undefined 时映射。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#registry',
    },
  },
  {
    id: 13,
    category: 'FormApi',
    name: 'submit',
    modern: {
      status: '有意差异',
      note: '所有 submit 入口均校验，失败返回 undefined 且不调用业务提交；修正本地 Vben 直接 submit 的无效提交路径。隐藏停规则，查询折叠仍验证。',
      source: 'src/libs/form/core/api.ts',
      evidence:
        'tests/unit/schema-form-api.spec.ts; src/labs/form-engine/schema-experiments.ts#submit',
    },
  },
  {
    id: 14,
    category: 'FormApi',
    name: 'clearValidation',
    modern: {
      status: '已实现',
      note: 'clearValidation 支持全部/单字段/数组，清手工和规则错误并使旧异步校验失效。',
      source: 'src/libs/form/core/runtime.ts',
      evidence: 'tests/unit/schema-form-lifecycle.spec.ts',
    },
  },
  {
    id: 15,
    category: 'FormApi',
    name: 'updateSchema',
    modern: {
      status: '已实现',
      note: 'updateSchema 深配置合并，含分组和数组子 schema；数组替换，null/undefined 按参考配置 fallback。',
      source: 'src/libs/form/core/api.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts',
    },
  },
  {
    id: 16,
    category: 'FormApi',
    name: 'setSubmitValues',
    modern: {
      status: '已实现',
      note: 'codec encode/decode、setSubmitValues；提交值和原始值类型独立，解析不改写模型。',
      source: 'src/libs/form/core/api.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts',
    },
  },
  {
    id: 17,
    category: 'FormApi',
    name: 'validateAndSubmit',
    modern: {
      status: '已实现',
      note: 'validateAndSubmit 校验失败返回 undefined，成功等待 handleSubmit 并返回提交值。',
      source: 'src/libs/form/core/api.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts',
    },
  },
  {
    id: 18,
    category: 'FormApi',
    name: 'reset',
    modern: {
      status: '已实现',
      note: 'reset({values}, {force,keepDefaultValues}) 对齐默认值合并、基线保留/替换，并取消旧校验。',
      source: 'src/libs/form/core/api.ts; src/libs/form/core/runtime.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts; tests/unit/schema-form-lifecycle.spec.ts',
    },
  },
  {
    id: 19,
    category: 'FormApi',
    name: 'setValues',
    modern: {
      status: '已实现',
      note: 'setValues 默认过滤未知字段、对象深补丁、数组整体替换；filterFields=false 顶层分支赋值，第三参数默认不验。',
      source: 'src/libs/form/core/api.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts',
    },
  },
  {
    id: 20,
    category: 'FormApi',
    name: 'setFieldValue',
    modern: {
      status: '已实现',
      note: 'setFieldValue 挂载等待，第三参数 boolean 默认 false；程序赋值保留手工错误。',
      source: 'src/libs/form/core/api.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts; tests/unit/schema-form-lifecycle.spec.ts',
    },
  },
  {
    id: 21,
    category: 'FormApi',
    name: 'getValues',
    modern: {
      status: '已实现',
      note: 'Promise getter 等待挂载；getValueSnapshot 一次边界取得 rawValues/values 独立快照；formatValues 同步编码指定值。',
      source: 'src/libs/form/core/api.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts',
    },
  },
  {
    id: 22,
    category: 'FormApi',
    name: 'getRawValues',
    modern: {
      status: '已实现',
      note: 'Promise getter 等待挂载；getValueSnapshot 一次边界取得 rawValues/values 独立快照；formatValues 同步编码指定值。',
      source: 'src/libs/form/core/api.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts',
    },
  },
  {
    id: 23,
    category: 'FormApi',
    name: 'validate',
    modern: {
      status: '已实现',
      note: 'validate/validateField 返回 {valid,errors}；不以普通规则失败抛异常，执行异常/取消仍拒绝。',
      source: 'src/libs/form/core/api.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts; tests/unit/schema-form-lifecycle.spec.ts',
    },
  },
  {
    id: 24,
    category: 'FormApi',
    name: 'validateField',
    modern: {
      status: '已实现',
      note: 'validate/validateField 返回 {valid,errors}；不以普通规则失败抛异常，执行异常/取消仍拒绝。',
      source: 'src/libs/form/core/api.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts; tests/unit/schema-form-lifecycle.spec.ts',
    },
  },
  {
    id: 25,
    category: 'FormApi',
    name: 'isFieldValid',
    modern: {
      status: '已实现',
      note: 'isFieldValid 仅读现有错误，不主动重新校验；高层方法等待挂载。',
      source: 'src/libs/form/core/api.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts',
    },
  },
  {
    id: 26,
    category: 'FormApi',
    name: 'setState',
    modern: {
      status: '已实现',
      note: 'setState 支持对象/函数 patch，getState 同步读取完整状态；公开 store/useStore，数组替换。',
      source: 'src/libs/form/core/api.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts',
    },
  },
  {
    id: 27,
    category: 'FormApi',
    name: 'getState',
    modern: {
      status: '已实现',
      note: 'setState 支持对象/函数 patch，getState 同步读取完整状态；公开 store/useStore，数组替换。',
      source: 'src/libs/form/core/api.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts',
    },
  },
  {
    id: 28,
    category: 'FormApi',
    name: 'removeSchemaByFields',
    modern: {
      status: '已实现',
      note: 'removeSchemaByFields 移除字段和组内字段、保留分组壳；减少字段时对应值变 undefined，手工错误按路径保留。',
      source: 'src/libs/form/core/api.ts; src/libs/form/core/runtime.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts; tests/unit/schema-form-lifecycle.spec.ts',
    },
  },
  {
    id: 29,
    category: 'FormApi',
    name: 'getValueSnapshot',
    modern: {
      status: '已实现',
      note: 'Promise getter 等待挂载；getValueSnapshot 一次边界取得 rawValues/values 独立快照；formatValues 同步编码指定值。',
      source: 'src/libs/form/core/api.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts',
    },
  },
  {
    id: 30,
    category: 'FormApi',
    name: 'formatValues',
    modern: {
      status: '已实现',
      note: 'Promise getter 等待挂载；getValueSnapshot 一次边界取得 rawValues/values 独立快照；formatValues 同步编码指定值。',
      source: 'src/libs/form/core/api.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts',
    },
  },
  {
    id: 31,
    category: 'FormApi',
    name: 'form',
    modern: {
      status: '已实现',
      note: '公开 FormContextApi：values/errors/meta、字段操作、数组操作、校验和 fieldComponent。',
      source: 'src/libs/form/core/runtime.ts; src/libs/form/core/runtime-field.ts',
      evidence:
        'tests/unit/schema-form-api.spec.ts; src/labs/form-engine/schema-experiments.ts#field-component',
    },
  },
  {
    id: 32,
    category: 'FormApi',
    name: 'getFieldComponentRef',
    modern: {
      status: '已实现',
      note: '组件 ref、异步组件引用解包、getFocusedField；原生 form 属性名冲突有保护。',
      source: 'src/libs/form/core/api.ts; src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#focus',
    },
  },
  {
    id: 33,
    category: 'FormApi',
    name: 'getFocusedField',
    modern: {
      status: '已实现',
      note: '组件 ref、异步组件引用解包、getFocusedField；原生 form 属性名冲突有保护。',
      source: 'src/libs/form/core/api.ts; src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#focus',
    },
  },
  {
    id: 34,
    category: 'FormApi',
    name: 'submitForm / validateAndSubmitForm / resetForm / resetValidate',
    modern: {
      status: '排除',
      note: '废弃别名、旧格式化配置/类型、旧联动多回调不支持；使用现代 API、codec、dependencies.resolve。',
      source: 'src/libs/form/types.ts',
      evidence: '公开类型与排除范围审查',
    },
  },
  {
    id: 35,
    category: '响应式读取',
    name: 'useFieldValue',
    modern: {
      status: '已实现',
      note: '公开 useFieldValue/useFieldValues/useFieldError/useValues/useSelector；多字段无关变更保持引用稳定。',
      source: 'src/libs/form/core/runtime.ts',
      evidence:
        'tests/unit/schema-form-lifecycle.spec.ts; src/labs/form-engine/schema-experiments.ts#subscriptions',
    },
  },
  {
    id: 36,
    category: '响应式读取',
    name: 'useFieldValues',
    modern: {
      status: '已实现',
      note: '公开 useFieldValue/useFieldValues/useFieldError/useValues/useSelector；多字段无关变更保持引用稳定。',
      source: 'src/libs/form/core/runtime.ts',
      evidence:
        'tests/unit/schema-form-lifecycle.spec.ts; src/labs/form-engine/schema-experiments.ts#subscriptions',
    },
  },
  {
    id: 37,
    category: '响应式读取',
    name: 'useFieldError',
    modern: {
      status: '已实现',
      note: '公开 useFieldValue/useFieldValues/useFieldError/useValues/useSelector；多字段无关变更保持引用稳定。',
      source: 'src/libs/form/core/runtime.ts',
      evidence:
        'tests/unit/schema-form-lifecycle.spec.ts; src/labs/form-engine/schema-experiments.ts#subscriptions',
    },
  },
  {
    id: 38,
    category: '响应式读取',
    name: 'useValues',
    modern: {
      status: '已实现',
      note: '公开 useFieldValue/useFieldValues/useFieldError/useValues/useSelector；多字段无关变更保持引用稳定。',
      source: 'src/libs/form/core/runtime.ts',
      evidence:
        'tests/unit/schema-form-lifecycle.spec.ts; src/labs/form-engine/schema-experiments.ts#subscriptions',
    },
  },
  {
    id: 39,
    category: '响应式读取',
    name: 'useSelector',
    modern: {
      status: '已实现',
      note: '公开 useFieldValue/useFieldValues/useFieldError/useValues/useSelector；多字段无关变更保持引用稳定。',
      source: 'src/libs/form/core/runtime.ts',
      evidence:
        'tests/unit/schema-form-lifecycle.spec.ts; src/labs/form-engine/schema-experiments.ts#subscriptions',
    },
  },
  {
    id: 40,
    category: 'Props',
    name: 'layout',
    modern: {
      status: '已实现',
      note: 'layout 默认 horizontal，支持 vertical/inline，沿用 antdv-next 外观。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#theme',
    },
  },
  {
    id: 41,
    category: 'Props',
    name: 'showCollapseButton',
    modern: {
      status: '已实现',
      note: '查询折叠按真实栅格行，默认 collapsedRows=1；回调、resize 通知、响应式测量；折叠不关闭规则。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#fold-layout',
    },
  },
  {
    id: 42,
    category: 'Props',
    name: 'codec',
    modern: {
      status: '已实现',
      note: 'codec encode/decode、setSubmitValues；提交值和原始值类型独立，解析不改写模型。',
      source: 'src/libs/form/core/api.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts',
    },
  },
  {
    id: 43,
    category: 'Props',
    name: 'showDefaultActions',
    modern: {
      status: '已实现',
      note: '默认操作区、actionLayout/Position/WrapperClass、按钮反转及按钮内容/显隐/props 配置。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#actions',
    },
  },
  {
    id: 44,
    category: 'Props',
    name: 'collapsed',
    modern: {
      status: '已实现',
      note: '查询折叠按真实栅格行，默认 collapsedRows=1；回调、resize 通知、响应式测量；折叠不关闭规则。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#fold-layout',
    },
  },
  {
    id: 45,
    category: 'Props',
    name: 'schema',
    modern: {
      status: '已实现',
      note: '现代 FormSchema 联合类型支持 field/group/array，并支持挂载前和运行中 schema 更新。',
      source: 'src/libs/form/types.ts; src/libs/form/core/api.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts; tests/unit/schema-form-lifecycle.spec.ts',
    },
  },
  {
    id: 46,
    category: 'Props',
    name: 'wrapperClass',
    modern: {
      status: '已实现',
      note: 'wrapperClass 使用 grid/flex 布局；独立 CSS 提供常见响应式栅格，其他任意宿主 utility 类仍由宿主生成。',
      source: 'src/libs/form/core/render.ts; src/libs/form/core/grid.css',
      evidence:
        'src/labs/form-engine/schema-experiments.ts#fold-layout; scripts/form/check-schema-form-standalone.mjs',
    },
  },
  {
    id: 47,
    category: 'Props',
    name: 'handleReset',
    modern: {
      status: '已实现',
      note: '重置按钮先取格式化旧值；handleReset 接管默认重置；直接 api.reset 不调用该回调。',
      source: 'src/libs/form/core/api.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#actions',
    },
  },
  {
    id: 48,
    category: 'Props',
    name: 'handleSubmit',
    modern: {
      status: '已实现',
      note: 'handleSubmit(values,rawValues) 两种独立快照，等待业务回调；第二参数不再占用取消上下文。',
      source: 'src/libs/form/core/api.ts',
      evidence:
        'tests/unit/schema-form-api.spec.ts; src/labs/form-engine/schema-experiments.ts#submit',
    },
  },
  {
    id: 49,
    category: 'Props',
    name: 'handleValuesChange',
    modern: {
      status: '已实现',
      note: 'handleValuesChange(readonlyValues,changedFields,lazyFormat)，批次通知、声明字段比较，第三参数按调用格式化。',
      source: 'src/libs/form/core/runtime.ts',
      evidence: 'tests/unit/schema-form-lifecycle.spec.ts',
    },
  },
  {
    id: 50,
    category: 'Props',
    name: 'collapsedRows',
    modern: {
      status: '已实现',
      note: '查询折叠按真实栅格行，默认 collapsedRows=1；回调、resize 通知、响应式测量；折叠不关闭规则。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#fold-layout',
    },
  },
  {
    id: 51,
    category: 'Props',
    name: 'submitOnEnter',
    modern: {
      status: '已实现',
      note: 'submitOnEnter 默认 false；开启后提交并校验，跳过 textarea；保留输入法组合态保护。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#actions',
    },
  },
  {
    id: 52,
    category: 'Props',
    name: 'scrollToFirstError',
    modern: {
      status: '已实现',
      note: 'scrollToFirstError 默认 false；validate/validateField 失败可滚动；不强制抢焦点。',
      source: 'src/libs/form/core/api.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#focus; #group',
    },
  },
  {
    id: 53,
    category: 'Props',
    name: 'actionWrapperClass',
    modern: {
      status: '已实现',
      note: '默认操作区、actionLayout/Position/WrapperClass、按钮反转及按钮内容/显隐/props 配置。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#actions',
    },
  },
  {
    id: 54,
    category: 'Props',
    name: 'actionLayout',
    modern: {
      status: '已实现',
      note: '默认操作区、actionLayout/Position/WrapperClass、按钮反转及按钮内容/显隐/props 配置。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#actions',
    },
  },
  {
    id: 55,
    category: 'Props',
    name: 'actionPosition',
    modern: {
      status: '已实现',
      note: '默认操作区、actionLayout/Position/WrapperClass、按钮反转及按钮内容/显隐/props 配置。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#actions',
    },
  },
  {
    id: 56,
    category: 'Props',
    name: 'handleCollapsedChange',
    modern: {
      status: '已实现',
      note: '查询折叠按真实栅格行，默认 collapsedRows=1；回调、resize 通知、响应式测量；折叠不关闭规则。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#fold-layout',
    },
  },
  {
    id: 57,
    category: 'Props',
    name: 'actionButtonsReverse',
    modern: {
      status: '已实现',
      note: '默认操作区、actionLayout/Position/WrapperClass、按钮反转及按钮内容/显隐/props 配置。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#actions',
    },
  },
  {
    id: 58,
    category: 'Props',
    name: 'resetButtonOptions',
    modern: {
      status: '已实现',
      note: '默认操作区、actionLayout/Position/WrapperClass、按钮反转及按钮内容/显隐/props 配置。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#actions',
    },
  },
  {
    id: 59,
    category: 'Props',
    name: 'submitButtonOptions',
    modern: {
      status: '已实现',
      note: '默认操作区、actionLayout/Position/WrapperClass、按钮反转及按钮内容/显隐/props 配置。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#actions',
    },
  },
  {
    id: 60,
    category: 'Props',
    name: 'collapseTriggerResize',
    modern: {
      status: '已实现',
      note: '查询折叠按真实栅格行，默认 collapsedRows=1；回调、resize 通知、响应式测量；折叠不关闭规则。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#fold-layout',
    },
  },
  {
    id: 61,
    category: 'Props',
    name: 'submitOnChange',
    modern: {
      status: '已实现',
      note: 'submitOnChange 防抖自动校验提交，changeDebouncedTime 默认 300ms，卸载取消定时器。',
      source: 'src/libs/form/core/runtime.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts',
    },
  },
  {
    id: 62,
    category: 'Props',
    name: 'compact',
    modern: {
      status: '已实现',
      note: 'compact 布局压缩字段底部间距。',
      source: 'src/libs/form/core/style.css',
      evidence: 'src/labs/form-engine/schema-experiments.ts#theme',
    },
  },
  {
    id: 63,
    category: 'Props',
    name: 'commonConfig',
    modern: {
      status: '已实现',
      note: '公共→字段→动态 componentProps 合并，支持同步函数及字段/行上下文；disabled 向数组子项继承。',
      source: 'src/libs/form/core/runtime.ts; src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#slots; #array',
    },
  },
  {
    id: 64,
    category: '旧格式化',
    name: 'fieldMappingTime',
    modern: {
      status: '排除',
      note: '废弃别名、旧格式化配置/类型、旧联动多回调不支持；使用现代 API、codec、dependencies.resolve。',
      source: 'src/libs/form/types.ts',
      evidence: '公开类型与排除范围审查',
    },
  },
  {
    id: 65,
    category: '旧格式化',
    name: 'arrayToStringFields',
    modern: {
      status: '排除',
      note: '废弃别名、旧格式化配置/类型、旧联动多回调不支持；使用现代 API、codec、dependencies.resolve。',
      source: 'src/libs/form/types.ts',
      evidence: '公开类型与排除范围审查',
    },
  },
  {
    id: 66,
    category: '旧格式化',
    name: 'schema.valueFormat / FormValueFormat',
    modern: {
      status: '排除',
      note: '废弃别名、旧格式化配置/类型、旧联动多回调不支持；使用现代 API、codec、dependencies.resolve。',
      source: 'src/libs/form/types.ts',
      evidence: '公开类型与排除范围审查',
    },
  },
  {
    id: 67,
    category: 'FormCommonConfig',
    name: 'disabled',
    modern: {
      status: '已实现',
      note: '公共→字段→动态 componentProps 合并，支持同步函数及字段/行上下文；disabled 向数组子项继承。',
      source: 'src/libs/form/core/runtime.ts; src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#slots; #array',
    },
  },
  {
    id: 68,
    category: 'FormCommonConfig',
    name: 'componentProps',
    modern: {
      status: '已实现',
      note: '公共→字段→动态 componentProps 合并，支持同步函数及字段/行上下文；disabled 向数组子项继承。',
      source: 'src/libs/form/core/runtime.ts; src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#slots; #array',
    },
  },
  {
    id: 69,
    category: 'FormCommonConfig',
    name: 'modelPropName',
    modern: {
      status: '已实现',
      note: '支持 baseModelPropName、modelPropNameMap 和字段 modelPropName；antd 控件内置模型映射。',
      source: 'src/libs/form/controls.ts; src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#registry',
    },
  },
  {
    id: 70,
    category: 'FormCommonConfig',
    name: 'formFieldProps',
    modern: {
      status: '已实现',
      note: 'formFieldProps.validateOn/asyncDebounceMs；默认 blur/change，submit 始终验证且不等防抖；取消旧结果。',
      source: 'src/libs/form/core/runtime.ts',
      evidence: 'tests/unit/schema-form-lifecycle.spec.ts; tests/unit/schema-form-api.spec.ts',
    },
  },
  {
    id: 71,
    category: 'FormCommonConfig',
    name: 'labelWidth',
    modern: {
      status: '已实现',
      note: 'labelWidth 支持 number/string/auto，vertical 或 labelClass 含 w- 时不强加宽度。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#theme',
    },
  },
  {
    id: 72,
    category: 'FormCommonConfig',
    name: 'controlClass',
    modern: {
      status: '已实现',
      note: 'controlClass/colon/formItemClass/hideLabel/hideRequiredMark/wrapperClass 分层渲染。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#slots; #theme; #fold-layout',
    },
  },
  {
    id: 73,
    category: 'FormCommonConfig',
    name: 'colon',
    modern: {
      status: '已实现',
      note: 'controlClass/colon/formItemClass/hideLabel/hideRequiredMark/wrapperClass 分层渲染。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#slots; #theme; #fold-layout',
    },
  },
  {
    id: 74,
    category: 'FormCommonConfig',
    name: 'formItemClass',
    modern: {
      status: '已实现',
      note: 'controlClass/colon/formItemClass/hideLabel/hideRequiredMark/wrapperClass 分层渲染。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#slots; #theme; #fold-layout',
    },
  },
  {
    id: 75,
    category: 'FormCommonConfig',
    name: 'hideLabel',
    modern: {
      status: '已实现',
      note: 'controlClass/colon/formItemClass/hideLabel/hideRequiredMark/wrapperClass 分层渲染。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#slots; #theme; #fold-layout',
    },
  },
  {
    id: 76,
    category: 'FormCommonConfig',
    name: 'hideRequiredMark',
    modern: {
      status: '已实现',
      note: 'controlClass/colon/formItemClass/hideLabel/hideRequiredMark/wrapperClass 分层渲染。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#slots; #theme; #fold-layout',
    },
  },
  {
    id: 77,
    category: 'FormCommonConfig',
    name: 'labelClass',
    modern: {
      status: '已实现',
      note: 'labelWidth 支持 number/string/auto，vertical 或 labelClass 含 w- 时不强加宽度。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#theme',
    },
  },
  {
    id: 78,
    category: 'FormCommonConfig',
    name: 'wrapperClass',
    modern: {
      status: '已实现',
      note: 'controlClass/colon/formItemClass/hideLabel/hideRequiredMark/wrapperClass 分层渲染。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#slots; #theme; #fold-layout',
    },
  },
  {
    id: 79,
    category: 'FormCommonConfig',
    name: 'changeEventFallback',
    modern: {
      status: '已实现',
      note: 'changeEventFallback 支持仅 change 的控件；相同值不重复写入，保留用户事件回调。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#registry',
    },
  },
  {
    id: 80,
    category: 'FormFieldSchema',
    name: 'component',
    modern: {
      status: '已实现',
      note: '内置 antdv-next 控件映射、组件对象及注册别名，支持 AutoComplete/Mentions/按钮等。',
      source: 'src/libs/form/controls.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#registry; schema-experiments.ts',
    },
  },
  {
    id: 81,
    category: 'FormFieldSchema',
    name: 'defaultValue',
    modern: {
      status: '已实现',
      note: '显式 defaultValue 优先，Zod 默认值合并；挂载时按最新 schema 生成一次。',
      source: 'src/libs/form/core/runtime.ts; src/libs/form/internal/zod.ts',
      evidence: 'tests/unit/schema-form-lifecycle.spec.ts; tests/unit/schema-form-api.spec.ts',
    },
  },
  {
    id: 82,
    category: 'FormFieldSchema',
    name: 'fieldName',
    modern: {
      status: '已实现',
      note: '嵌套对象、数组索引、字面量点号路径；数组子项支持 $root/$row。',
      source: 'src/libs/form/core/helpers.ts',
      evidence: 'tests/unit/schema-form-api.spec.ts',
    },
  },
  {
    id: 83,
    category: 'FormFieldSchema',
    name: 'componentProps',
    modern: {
      status: '已实现',
      note: '公共→字段→动态 componentProps 合并，支持同步函数及字段/行上下文；disabled 向数组子项继承。',
      source: 'src/libs/form/core/runtime.ts; src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#slots; #array',
    },
  },
  {
    id: 84,
    category: 'FormFieldSchema',
    name: 'dependencies',
    modern: {
      status: '已实现',
      note: '现代 resolve({values,actions,controller,schema})，支持异步、if/show/disabled/required/rules/props/help/内容；旧异步结果失效且不阻塞新提交。',
      source: 'src/libs/form/core/runtime.ts',
      evidence:
        'tests/unit/schema-form-api.spec.ts; tests/unit/schema-form-lifecycle.spec.ts; src/labs/form-engine/schema-experiments.ts#visibility',
    },
  },
  {
    id: 85,
    category: 'FormFieldSchema',
    name: 'help',
    modern: {
      status: '已实现',
      note: 'label/help/description/suffix 渲染函数、字段上下文、动态 help 与控件子插槽。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#slots',
    },
  },
  {
    id: 86,
    category: 'FormFieldSchema',
    name: 'hide',
    modern: {
      status: '已实现',
      note: 'hide/if 卸载控件，show 仅 CSS 隐藏；隐藏停用规则并保值/可赋值/可提交，手工错误仍需显式清除。',
      source: 'src/libs/form/core/runtime.ts; src/libs/form/core/render.ts',
      evidence:
        'tests/unit/schema-form-lifecycle.spec.ts; src/labs/form-engine/schema-experiments.ts#visibility',
    },
  },
  {
    id: 87,
    category: 'FormFieldSchema',
    name: 'label',
    modern: {
      status: '已实现',
      note: 'label/help/description/suffix 渲染函数、字段上下文、动态 help 与控件子插槽。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#slots',
    },
  },
  {
    id: 88,
    category: 'FormFieldSchema',
    name: 'rules',
    modern: {
      status: '已实现',
      note: 'Zod4 safeParseAsync、命名 required/selectRequired/自定义规则；首条错误、不写 parsed 输出；必填拆包装/pipe 输入及 isOptional 星号。',
      source: 'src/libs/form/core/runtime.ts; src/libs/form/config.ts',
      evidence:
        'tests/unit/schema-form-api.spec.ts; src/labs/form-engine/schema-experiments.ts#submit',
    },
  },
  {
    id: 89,
    category: 'FormFieldSchema',
    name: 'description',
    modern: {
      status: '已实现',
      note: 'label/help/description/suffix 渲染函数、字段上下文、动态 help 与控件子插槽。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#slots',
    },
  },
  {
    id: 90,
    category: 'FormFieldSchema',
    name: 'renderComponentContent',
    modern: {
      status: '已实现',
      note: 'label/help/description/suffix 渲染函数、字段上下文、动态 help 与控件子插槽。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#slots',
    },
  },
  {
    id: 91,
    category: 'FormFieldSchema',
    name: 'suffix',
    modern: {
      status: '已实现',
      note: 'label/help/description/suffix 渲染函数、字段上下文、动态 help 与控件子插槽。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#slots',
    },
  },
  {
    id: 92,
    category: 'FormGroupSchema',
    name: 'type / children',
    modern: {
      status: '已实现',
      note: 'type:group/children、独立折叠、错误自动展开、title/extra、class、hide/name；隐藏保值停规则。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#group',
    },
  },
  {
    id: 93,
    category: 'FormGroupSchema',
    name: 'collapsible / defaultCollapsed',
    modern: {
      status: '已实现',
      note: 'type:group/children、独立折叠、错误自动展开、title/extra、class、hide/name；隐藏保值停规则。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#group',
    },
  },
  {
    id: 94,
    category: 'FormGroupSchema',
    name: 'extra / title',
    modern: {
      status: '已实现',
      note: 'type:group/children、独立折叠、错误自动展开、title/extra、class、hide/name；隐藏保值停规则。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#group',
    },
  },
  {
    id: 95,
    category: 'FormGroupSchema',
    name: 'formItemClass / wrapperClass',
    modern: {
      status: '已实现',
      note: 'type:group/children、独立折叠、错误自动展开、title/extra、class、hide/name；隐藏保值停规则。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#group',
    },
  },
  {
    id: 96,
    category: 'FormGroupSchema',
    name: 'hide / name',
    modern: {
      status: '已实现',
      note: 'type:group/children、独立折叠、错误自动展开、title/extra、class、hide/name；隐藏保值停规则。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#group',
    },
  },
  {
    id: 97,
    category: '联动',
    name: 'triggerFields / resolve',
    modern: {
      status: '已实现',
      note: '现代 resolve({values,actions,controller,schema})，支持异步、if/show/disabled/required/rules/props/help/内容；旧异步结果失效且不阻塞新提交。',
      source: 'src/libs/form/core/runtime.ts',
      evidence:
        'tests/unit/schema-form-api.spec.ts; tests/unit/schema-form-lifecycle.spec.ts; src/labs/form-engine/schema-experiments.ts#visibility',
    },
  },
  {
    id: 98,
    category: '联动',
    name: 'if / show / disabled / required',
    modern: {
      status: '已实现',
      note: '现代 resolve({values,actions,controller,schema})，支持异步、if/show/disabled/required/rules/props/help/内容；旧异步结果失效且不阻塞新提交。',
      source: 'src/libs/form/core/runtime.ts',
      evidence:
        'tests/unit/schema-form-api.spec.ts; tests/unit/schema-form-lifecycle.spec.ts; src/labs/form-engine/schema-experiments.ts#visibility',
    },
  },
  {
    id: 99,
    category: '联动',
    name: 'rules:null / componentProps',
    modern: {
      status: '已实现',
      note: '现代 resolve({values,actions,controller,schema})，支持异步、if/show/disabled/required/rules/props/help/内容；旧异步结果失效且不阻塞新提交。',
      source: 'src/libs/form/core/runtime.ts',
      evidence:
        'tests/unit/schema-form-api.spec.ts; tests/unit/schema-form-lifecycle.spec.ts; src/labs/form-engine/schema-experiments.ts#visibility',
    },
  },
  {
    id: 100,
    category: '联动',
    name: 'help / renderComponentContent',
    modern: {
      status: '已实现',
      note: '现代 resolve({values,actions,controller,schema})，支持异步、if/show/disabled/required/rules/props/help/内容；旧异步结果失效且不阻塞新提交。',
      source: 'src/libs/form/core/runtime.ts',
      evidence:
        'tests/unit/schema-form-api.spec.ts; tests/unit/schema-form-lifecycle.spec.ts; src/labs/form-engine/schema-experiments.ts#visibility',
    },
  },
  {
    id: 101,
    category: '联动',
    name: 'values / actions / controller / schema 上下文',
    modern: {
      status: '已实现',
      note: '现代 resolve({values,actions,controller,schema})，支持异步、if/show/disabled/required/rules/props/help/内容；旧异步结果失效且不阻塞新提交。',
      source: 'src/libs/form/core/runtime.ts',
      evidence:
        'tests/unit/schema-form-api.spec.ts; tests/unit/schema-form-lifecycle.spec.ts; src/labs/form-engine/schema-experiments.ts#visibility',
    },
  },
  {
    id: 102,
    category: '联动',
    name: '旧 if/show/disabled/required/rules/componentProps/trigger 回调',
    modern: {
      status: '排除',
      note: '废弃别名、旧格式化配置/类型、旧联动多回调不支持；使用现代 API、codec、dependencies.resolve。',
      source: 'src/libs/form/types.ts',
      evidence: '公开类型与排除范围审查',
    },
  },
  {
    id: 103,
    category: '校验',
    name: 'required / selectRequired 用途',
    modern: {
      status: '已实现',
      note: 'Zod4 safeParseAsync、命名 required/selectRequired/自定义规则；首条错误、不写 parsed 输出；必填拆包装/pipe 输入及 isOptional 星号。',
      source: 'src/libs/form/core/runtime.ts; src/libs/form/config.ts',
      evidence:
        'tests/unit/schema-form-api.spec.ts; src/labs/form-engine/schema-experiments.ts#submit',
    },
  },
  {
    id: 104,
    category: '校验',
    name: 'blur/change/submit / asyncDebounceMs',
    modern: {
      status: '已实现',
      note: 'formFieldProps.validateOn/asyncDebounceMs；默认 blur/change，submit 始终验证且不等防抖；取消旧结果。',
      source: 'src/libs/form/core/runtime.ts',
      evidence: 'tests/unit/schema-form-lifecycle.spec.ts; tests/unit/schema-form-api.spec.ts',
    },
  },
  {
    id: 105,
    category: '校验',
    name: '邮箱 / min / refine / 跨字段',
    modern: {
      status: '已实现',
      note: 'Zod4 safeParseAsync、命名 required/selectRequired/自定义规则；首条错误、不写 parsed 输出；必填拆包装/pipe 输入及 isOptional 星号。',
      source: 'src/libs/form/core/runtime.ts; src/libs/form/config.ts',
      evidence:
        'tests/unit/schema-form-api.spec.ts; src/labs/form-engine/schema-experiments.ts#submit',
    },
  },
  {
    id: 106,
    category: '校验',
    name: 'rules: zod schema / z 导出',
    modern: {
      status: '已实现',
      note: 'Zod4 safeParseAsync、命名 required/selectRequired/自定义规则；首条错误、不写 parsed 输出；必填拆包装/pipe 输入及 isOptional 星号。',
      source: 'src/libs/form/core/runtime.ts; src/libs/form/config.ts',
      evidence:
        'tests/unit/schema-form-api.spec.ts; src/labs/form-engine/schema-experiments.ts#submit',
    },
  },
  {
    id: 107,
    category: '校验',
    name: '全局命名规则注册',
    modern: {
      status: '已实现',
      note: 'Zod4 safeParseAsync、命名 required/selectRequired/自定义规则；首条错误、不写 parsed 输出；必填拆包装/pipe 输入及 isOptional 星号。',
      source: 'src/libs/form/core/runtime.ts; src/libs/form/config.ts',
      evidence:
        'tests/unit/schema-form-api.spec.ts; src/labs/form-engine/schema-experiments.ts#submit',
    },
  },
  {
    id: 108,
    category: 'Slots',
    name: '字段名插槽',
    modern: {
      status: '已实现',
      note: '自动字段名插槽，完整 field/componentField/componentProps/modelValue/name/disabled/isInValid/values/formApi，字段泛型推导。',
      source: 'src/libs/form/core/render.ts; src/libs/form/types.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#slots; type-check',
    },
  },
  {
    id: 109,
    category: 'Slots',
    name: 'componentProps',
    modern: {
      status: '已实现',
      note: '自动字段名插槽，完整 field/componentField/componentProps/modelValue/name/disabled/isInValid/values/formApi，字段泛型推导。',
      source: 'src/libs/form/core/render.ts; src/libs/form/types.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#slots; type-check',
    },
  },
  {
    id: 110,
    category: 'Slots',
    name: 'field / componentField / modelValue / name / disabled / isInValid / values / formApi',
    modern: {
      status: '已实现',
      note: '自动字段名插槽，完整 field/componentField/componentProps/modelValue/name/disabled/isInValid/values/formApi，字段泛型推导。',
      source: 'src/libs/form/core/render.ts; src/libs/form/types.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#slots; type-check',
    },
  },
  {
    id: 111,
    category: 'Slots',
    name: 'default',
    modern: {
      status: '已实现',
      note: 'default(shapes,values,formApi) 和 reset-before/submit-before/expand-before/expand-after 操作区插槽。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#actions; #field-component',
    },
  },
  {
    id: 112,
    category: 'Slots',
    name: 'reset-before',
    modern: {
      status: '已实现',
      note: 'default(shapes,values,formApi) 和 reset-before/submit-before/expand-before/expand-after 操作区插槽。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#actions; #field-component',
    },
  },
  {
    id: 113,
    category: 'Slots',
    name: 'submit-before',
    modern: {
      status: '已实现',
      note: 'default(shapes,values,formApi) 和 reset-before/submit-before/expand-before/expand-after 操作区插槽。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#actions; #field-component',
    },
  },
  {
    id: 114,
    category: 'Slots',
    name: 'expand-before',
    modern: {
      status: '已实现',
      note: 'default(shapes,values,formApi) 和 reset-before/submit-before/expand-before/expand-after 操作区插槽。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#actions; #field-component',
    },
  },
  {
    id: 115,
    category: 'Slots',
    name: 'expand-after',
    modern: {
      status: '已实现',
      note: 'default(shapes,values,formApi) 和 reset-before/submit-before/expand-before/expand-after 操作区插槽。',
      source: 'src/libs/form/core/render.ts',
      evidence: 'src/labs/form-engine/schema-experiments.ts#actions; #field-component',
    },
  },
];
export const apiDocs = {
  getValues: {
    signature: '(): Promise<S>',
    note: '获取经过 codec 的提交值快照。',
    demo: 'query',
  },
  getRawValues: {
    signature: '(): Promise<T>',
    note: '获取原始模型的独立快照。',
    demo: 'api',
  },
  getValueSnapshot: {
    signature: '(): Promise<{ rawValues: Readonly<T>; values: S }>',
    note: '一次读取原始值与提交值。',
    demo: 'api',
  },
  setValues: {
    signature: '(values, filterFields = true, shouldValidate = false): Promise<void>',
    note: '默认按 schema 过滤，深对象合并、数组替换；false 使用顶层分支替换。可选异步校验不由此 Promise 等待，需要结果时显式 validate。',
    demo: 'api',
  },
  setFieldValue: {
    signature: '(name, value, shouldValidate = false): Promise<void>',
    note: '赋值单字段；默认不校验。',
    demo: 'api',
  },
  setSubmitValues: {
    signature: '(payload: S, filterFields?, shouldValidate?): Promise<void>',
    note: 'codec.decode 后回填。',
    demo: 'query',
  },
  validate: {
    signature: '(): Promise<FormValidationResult>',
    note: '返回 { valid, errors }，校验失败不抛字段异常。',
    demo: 'rules',
  },
  validateField: {
    signature: '(name): Promise<FormValidationResult>',
    note: '仅校验指定字段。',
    demo: 'rules',
  },
  submit: {
    signature: '(): Promise<S | undefined>',
    note: '所有提交均校验；无效返回 undefined，不调用 handleSubmit。业务异常仍拒绝 Promise。',
    demo: 'basic',
  },
  validateAndSubmit: {
    signature: '(): Promise<S | undefined>',
    note: '校验后提交，与 submit 共用一条执行路径。',
    demo: 'api',
  },
  reset: {
    signature: '({ values }?, { force, keepDefaultValues }?): Promise<void>',
    note: '重置值和校验；传 values 可建立新基线。',
    demo: 'api',
  },
  resetByButton: {
    signature: '(): Promise<void>',
    note: '执行 handleReset；配置回调时由回调接管默认重置。',
    demo: 'api',
  },
  setFieldError: {
    signature: '(name, error?): Promise<void>',
    note: '设置服务端错误，按路径保留；程序赋值不清除。',
    demo: 'api',
  },
  clearValidation: {
    signature: '(names?: string | string[]): Promise<void>',
    note: '清除指定或全部错误。',
    demo: 'api',
  },
  isFieldValid: {
    signature: '(name): Promise<boolean>',
    note: '只读取当前错误状态，不主动运行规则。',
    demo: 'api',
  },
  setState: {
    signature: '(patch | updater): void',
    note: '更新配置；动态新增字段使用 schema 数组。',
    demo: 'api',
  },
  getState: {
    signature: '(): SchemaFormProps',
    note: '读取当前完整配置。',
    demo: 'api',
  },
  state: {
    signature: 'SchemaFormProps',
    note: '当前配置；不是 Ref。',
    demo: 'api',
  },
  useStore: {
    signature: '(selector?): Readonly<Ref>',
    note: '订阅配置或选中的配置片段。',
    demo: 'api',
  },
  store: {
    signature: 'Store<SchemaFormProps>',
    note: '配置 store。',
    demo: 'api',
  },
  updateSchema: {
    signature: '(patches): void',
    note: '按字段名局部更新 schema，保留现有值。',
    demo: 'api',
  },
  removeSchemaByFields: {
    signature: '(names: string[]): Promise<void>',
    note: '删除字段 schema；遵循 Vben 的值清理语义。',
    demo: 'api',
  },
  getFieldComponentRef: {
    signature: '<R>(name): R | undefined',
    note: '获取真实控件引用，可调用该控件的 focus 等方法。',
    demo: 'api',
  },
  getFocusedField: {
    signature: '(): string | undefined',
    note: '返回当前聚焦字段名。',
    demo: 'api',
  },
  scrollToFirstError: {
    signature: '(errors | name): void',
    note: '滚动到错误字段。',
    demo: 'api',
  },
  getLatestSubmissionValues: {
    signature: '(): Partial<S>',
    note: '获取最近一次提交值的快照。',
    demo: 'api',
  },
  setLatestSubmissionValues: {
    signature: '(values: Partial<S> | null): void',
    note: '更新最近提交快照。',
    demo: 'api',
  },
  formatValues: {
    signature: '(rawValues: Readonly<T>): S',
    note: '同步执行提交投影与 codec。',
    demo: 'query',
  },
  form: {
    signature: 'FormContextApi<T>',
    note: '同步字段读值、错误/meta、字段选择器、pushFieldValue/removeFieldValue；useFormContext 获取相同上下文。',
    demo: 'groups',
  },
  merge: {
    signature: '(otherApi): ExtendedFormApi',
    note: '串联多个表单；submitAllForm 校验后合并取值，不执行业务提交回调。',
    demo: 'api',
  },
};
export const optionRows = [
  ['schema', 'FormSchema[]', '[]', '字段、分组或数组配置。'],
  ['wrapperClass', 'ClassType', 'grid-cols-1', '响应式 grid-cols-* 栅格。'],
  ['layout', 'horizontal | vertical | inline', 'horizontal', '布局。'],
  ['commonConfig', 'FormCommonConfig', '{}', '共享字段样式、标签、控件与事件配置。'],
  ['codec', 'FormCodec<T,S>', '—', '唯一提交转换边界。'],
  ['handleSubmit', '(values, rawValues) => void | Promise<void>', '—', '校验成功后执行业务提交。'],
  ['handleReset', '(values) => void | Promise<void>', '—', '重置按钮回调，接管默认 reset。'],
  [
    'handleValuesChange',
    '(values, fieldsChanged, getFormattedValues) => void',
    '—',
    '字段变化通知，按需读取提交值。',
  ],
  ['submitOnChange / submitOnEnter', 'boolean', 'false', '自动提交；仍执行校验。'],
  ['changeDebouncedTime', 'number', '300', '变化提交防抖。'],
  ['showDefaultActions', 'boolean', 'true', '显示操作区。'],
  [
    'submitButtonOptions / resetButtonOptions',
    'ActionButtonOptions',
    '{}',
    '按钮内容、显隐及组件属性。',
  ],
  ['showCollapseButton / collapsed', 'boolean', 'false', '查询折叠与开关。'],
  ['collapsedRows', 'number', '1', '按实际网格行计算折叠。'],
  [
    'actionLayout / actionPosition',
    'inline | newLine | rowEnd / center | left | right',
    '—',
    '操作区布局与位置。',
  ],
  ['scrollToFirstError', 'boolean', 'false', '无效提交时滚动到错误。'],
  ['locale', 'Partial<FormLocale>', 'zhCN', '单 UI 展示文案；规则错误在 Zod 或命名规则中定义。'],
];
export const fieldRows = [
  ['fieldName', 'string', '必填', '支持对象路径及数组行相对路径。'],
  ['component', 'string | Component', '必填', '内置控件、注册别名或组件对象。'],
  ['defaultValue', 'unknown', '—', '字段初值，与 Zod 输入默认值合并。'],
  ['rules', 'ZodType | string | null', '—', 'Zod 4 或命名规则；null 停用规则。'],
  [
    'dependencies',
    '{ triggerFields, resolve }',
    '—',
    'resolve({ values, actions, controller, schema }) 返回联动状态。',
  ],
  ['hide', 'boolean', 'false', '卸载控件，停校验，保值可提交。'],
  [
    'dependencies.resolve → if / show',
    'boolean',
    'true',
    'if=false 卸载；show=false CSS 隐藏保留控件；两者停规则、保值。',
  ],
  ['componentProps', 'object | (context) => object', '{}', '控件属性。'],
  ['formFieldProps', '{ validateOn, asyncDebounceMs }', '—', 'change/blur 校验与异步防抖。'],
  ['type', 'group | array', '—', '分组或动态数组；children 描述内部字段。'],
  ['arrayProps', 'VbenFormFieldArrayProps', '—', '行数上下限、默认行、按钮文案等。'],
  ['label / help / description / suffix', 'CustomRenderType', '—', '标签、提示和附加内容。'],
  ['modelPropName', 'string', '按控件映射', '自定义模型属性名。'],
  ['formItemClass / controlClass', 'ClassType', '—', '字段容器或控件样式。'],
  ['submitWhenHidden', 'boolean', 'true', '本项目扩展：false 排除隐藏字段提交值。'],
];
export const uiRows = [
  ['disabled', 'boolean', 'false', '禁用控件仍校验。'],
  ['labelWidth', 'string | number', '—', '标签宽度或 auto。'],
  ['hideLabel / hideRequiredMark', 'boolean', 'false', '标签和必填标记显隐。'],
  ['emptyStateValue', 'null | undefined', 'undefined', '空值状态。'],
  ['changeEventFallback', 'boolean', 'false', '需要时兼容仅发 change 的自定义控件。'],
  ['formFieldProps', 'FormFieldOptions', '—', '共享校验触发设置。'],
];
